# Generated by Django 5.2.9 on 2026-01-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('seniority', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('SEARCH_DONE', 'Busca feita'), ('CANDIDATES_SENT', 'Candidatos enviados'), ('CLOSED', 'Vaga finalizada')], default='OPEN', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
