# Generated by Django 5.2.9 on 2026-01-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_contract_type_job_deadline_job_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='boolean_search',
            field=models.TextField(blank=True),
        ),
    ]
