# Generated by Django 5.2.10 on 2026-08-17 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_candidatejob_parecer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('VACANCY_IMPORT', 'Importação em vaga'), ('TALENT_POOL_IMPORT', 'Importação no banco de talentos'), ('POOL_SEARCH', 'Busca no banco de talentos')], max_length=32)),
                ('status', models.CharField(choices=[('RUNNING', 'Em andamento'), ('COMPLETED', 'Concluída'), ('ERROR', 'Falhou')], default='RUNNING', max_length=16)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'kind', '-started_at'], name='core_import_user_id_4223dd_idx')],
            },
        ),
    ]
