# Generated by Django 6.0.6 on 2026-08-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_candidate_linkedin_upper_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
