# Generated by Django 5.2.12 on 2026-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_importjob_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
