"""
Django settings for talent_query project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env", override=True)

CACHE_DIR = BASE_DIR / "cache"
CACHE_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# R-21: o default virou False. Esquecer de configurar passou a ser seguro por omissão —
# antes, um ambiente sem `.env` subia com DEBUG ligado, servindo traceback e SQL a quem
# provocasse um erro.
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes")

# R-21: a chave publicada no Git deixou de ser fallback silencioso em produção.
# Ela está no histórico do repositório desde o primeiro commit; qualquer um que leia o
# repo consegue forjar cookie de sessão e token de CSRF de quem estiver rodando com ela.
# Fora de DEBUG a aplicação agora **se recusa a subir** sem `DJANGO_SECRET_KEY` — falhar
# no boot é barulhento e recuperável em um minuto; rodar com a chave conhecida é silencioso
# e não tem sintoma nenhum até alguém abusar.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY é obrigatória quando DEBUG=False. "
            'Gere uma com: python -c "from django.core.management.utils import '
            'get_random_secret_key; print(get_random_secret_key())"'
        )
    SECRET_KEY = "django-insecure-somente-para-desenvolvimento-local"

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()
]

# Proxy/SSL (Lightsail + Nginx)
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
USE_X_FORWARDED_HOST = os.getenv("USE_X_FORWARDED_HOST", "False").lower() in ("1", "true", "yes")

# R-21: o default era "True" sempre, inclusive em desenvolvimento — onde não há proxy
# nenhum e confiar num header que qualquer cliente pode mandar é gratuito.
# Agora o default acompanha o DEBUG. Ligado fora de DEBUG **de propósito**, e não só
# quando a variável existir: o SECURE_SSL_REDIRECT abaixo depende deste header para saber
# que a requisição já chegou por HTTPS. Sem ele, o Nginx encaminharia em HTTP, o Django
# redirigiria para HTTPS, e o site entraria em laço infinito de redirect.
if os.getenv("DJANGO_SECURE_PROXY_SSL", str(not DEBUG)).lower() in ("1", "true", "yes"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# R-21: cookies e HTTPS obrigatórios fora de DEBUG. Fecha D-7.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    # HSTS começa em 1 hora, não em 1 ano, e sobe depois de o deploy provar que está
    # estável. O navegador **memoriza** esse prazo: publicar um ano e descobrir um
    # problema no HTTPS deixaria a usuária sem acesso, sem nada que o servidor possa
    # fazer para desfazer. Uma hora dá o mesmo benefício prático e expira sozinha.
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "3600"))
    # includeSubDomains e preload ficam de fora: o primeiro derruba qualquer subdomínio
    # que não esteja em HTTPS, o segundo é praticamente irreversível.


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.SingleSessionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "talent_query.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "talent_query.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "talent_query"),
        "USER": os.getenv("POSTGRES_USER", "talent_query"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "talent_query"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Cache compartilhado entre workers (importação/progresso)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": str(CACHE_DIR),
        "TIMEOUT": 60 * 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
# R-40. Era `STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"`,
# que o **Django removeu na 5.1** em favor de STORAGES. Producao roda 5.2.10, entao a
# linha estava sendo ignorada em silencio desde aquele upgrade: valia o StaticFilesStorage
# padrao, o collectstatic nao gerava .gz/.br e todo CSS e JS ia pela rede sem compressao.
#
# Com manifesto (e nao so `Compressed`) porque o nome do arquivo passa a levar hash do
# conteudo: o Whitenoise entao serve com cache imutavel, e editar um arquivo ja publicado
# nao corre risco de o browser continuar servindo a versao velha. E o que o plano ja
# supunha estar valendo, e o que o R-28 vai precisar quando editar CSS existente.
#
# So fora de DEBUG: o manifesto so existe depois do collectstatic, e exigir isso no
# runserver quebraria o desenvolvimento. O settings_test tambem forca o backend simples,
# para a suite nao depender de manifesto.
_MANIFESTO_DE_ESTATICOS = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": _MANIFESTO_DE_ESTATICOS},
}

# Media files (currículos PDF)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Busca no banco de talentos: score mínimo (0-100) do pré-match vaga x candidato
# para que o candidato seja enviado à LLM para avaliação final.
POOL_MATCH_MIN_SCORE = int(os.getenv("POOL_MATCH_MIN_SCORE", "40"))

# Timeout de cada chamada ao LLM, em SEGUNDOS (R-12).
# Sem isso uma chamada travada segura a thread de importacao para sempre: as threads
# sao daemon e nao tem cancelamento, entao a barra de progresso fica parada ate o
# proximo restart do servico.
# 180s e folgado de proposito. Um lote de 10 PDFs e a chamada mais cara do sistema, e
# timeout curto demais transforma importacao lenta em importacao que falha - trocaria
# um problema raro por um comum.
# ATENCAO: o SDK do Gemini recebe este valor em MILISSEGUNDOS (types.HttpOptions.timeout
# e documentado como "Timeout for the request in milliseconds"). A conversao acontece em
# core/llm_extractor.py::_generate. Nao passe este numero direto para o SDK.
LLM_TIMEOUT_SECONDS = int(os.getenv("LLM_TIMEOUT_SECONDS", "180"))

# Token do endpoint /metrics (R-22). Vazio = endpoint aberto, que era o comportamento
# ate aqui; preenchido = exige o token no header `X-Metrics-Token` ou em
# `Authorization: Bearer <token>`.
# O default vazio e proposital e e a metade "expand" do expand-contract: o codigo sobe
# sem derrubar nenhum scraper que ja consuma /metrics hoje. Fechar o endpoint em
# producao e preencher METRICS_TOKEN no .env e reiniciar o servico - nao precisa de
# outro deploy.
METRICS_TOKEN = os.getenv("METRICS_TOKEN", "").strip()

# Depois de quantos segundos sem heartbeat um job RUNNING e considerado morto (R-20b).
# As threads sao daemon: no `systemctl restart` do deploy elas somem sem rodar o
# `finally`, e antes disso a barra de progresso girava ate o cache expirar, uma hora
# depois.
# 15 minutos, e o numero e generoso de proposito. O heartbeat e escrito POR LOTE, nao por
# tempo: um lote vai ate 10 PDFs numa unica chamada ao LLM, com LLM_TIMEOUT_SECONDS de
# 180s e ate 4 tentativas — pode passar de 12 minutos sem sinal e estar vivo. Limiar curto
# trocaria um problema chato (barra girando a toa) por um pior: dizer que uma importacao
# viva morreu e fazer a recrutadora reiniciar tudo, pagando o LLM duas vezes.
IMPORT_JOB_STALE_AFTER_SECONDS = int(os.getenv("IMPORT_JOB_STALE_AFTER_SECONDS", "900"))

# Auth
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "home"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
